<?php
namespace App\Repository;
use Doctrine\ORM\EntityRepository;
/**
 * UserRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    public function deletedInactiveAccount()
    {
        //Query utilisée dans la commande DeleteUser
        $queryBuilder = $this->createQueryBuilder('u')
            ->delete('App:User', 'u')
            ->andWhere("u.accountActivationToken IS NOT NULL")

            //date de supp doit être plus récente que le paramètre 1
            ->andwhere("u.createdAt < ?1")

            //on set le paramètre avec lisDeleteda date du jour - 5 jours
            ->setParameter(1, date_modify(new \DateTime("now"), '-5 day'));

        $query = $queryBuilder->getQuery();
        $result = $query->getResult();

        return $result;
    }
}
